[project]
name = "pydata-ehv"
version = "0.1.0"
description = "Example package"
authors = ["Tom Monnier"]
channels = ["pytorch3d",  "pytorch","conda-forge","iopath", "anaconda", "default"]
platforms = ["linux-64"]

[system-requirements]
libc = "2.36"

[tasks]


[dependencies]
cudatoolkit="11.3.1"
ffmpeg={version= ">=4.3.2", channel = "conda-forge"}
fvcore="0.1.*"
imageio="2.21.1"
imageio-ffmpeg="0.4.8"
iopath="0.1.9"
numpy="1.23.4"
python=">=3.9"
pytorch="1.12.1"
pytorch3d= "0.7.1"
scipy="1.9.3"
seaborn= "0.12.0"
toolz= "0.12.0"
torchvision= "0.13.1"
x264= "1!161.3030"
opencv = "4.6.0"
cudnn = ">=8.8"

[pypi-dependencies]
gdown="==4.7.1"
lpips = "==0.1.4"
open3d = ">=0.16.0"
trimesh = "==3.15.8"